# This file was generated by GoReleaser. DO NOT EDIT.
class Devon < Formula
  desc "Devon, Redbubble's dev environment starter."
  homepage "https://github.com/redbubble/devon"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/redbubble/devon/releases/download/v0.0.1/devon_0.0.1_darwin_amd64.tar.gz"
    sha256 "c50384b5ef690f08c5f3bb221a38b4d5bafd44fe823df7b0b22aae5e626f3775"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/redbubble/devon/releases/download/v0.0.1/devon_0.0.1_linux_amd64.tar.gz"
      sha256 "84c447e92e2e76b66ec3d693d4b1b7423ccea73ebbbd132d486bc854f08290c6"
    end
  end

  def install
    bin.install "devon"
  end

  test do
    system "#{bin}/devon --version"
  end
end
