# This file was generated by GoReleaser. DO NOT EDIT.
class Devon < Formula
  desc "Devon, Redbubble's dev environment starter."
  homepage "https://github.com/redbubble/devon"
  version "0.0.1-pre5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/redbubble/devon/releases/download/v0.0.1-pre5/devon_0.0.1-pre5_darwin_amd64.tar.gz"
    sha256 "c96fe5495501abaed5bc2ad88dfc31335fd87a3f4b738c06377b3adfef6871f8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/redbubble/devon/releases/download/v0.0.1-pre5/devon_0.0.1-pre5_linux_amd64.tar.gz"
      sha256 "ae59397868a18eb7adaf28fe1fe9c352b37c35e752a7d2e9fe5c107b16dd070a"
    end
  end

  def install
    bin.install "devon"
  end

  test do
    system "#{bin}/devon --version"
  end
end
